startuppopupversion: 1
notARepository: "skip"
reporting: "off"
promptToReturnFromSubprocess: false

gui:
  theme:
    lightTheme: true
    selectedLineBgColor:
      - '#EDDEB5'
    selectedRangeBgColor:
      - reverse
    cherryPickedCommitBgColor:
      - reverse
  authorColors:
    '*': '#B47109'
  showFileTree: false
  showBottomLine: false

git:
  branchLogCmd: "git log --graph"
  paging:
    colorarg: always
    pager: delta --paging=never --diff-highlight
  
os:
  editPreset: 'nvim'
