disableStartupPopups: true
notARepository: "skip"
promptToReturnFromSubprocess: false
gui:
  theme:
    selectedLineBgColor:
      - '#EDDEB5'
    cherryPickedCommitBgColor:
      - reverse
  authorColors:
    '*': '#B47109'
  showFileTree: false
  useHunkModeInStagingView: false
git:
  branchLogCmd: "git log --graph"
  diffRenderers:
    - colorArg: always
      command: delta --paging=never --diff-highlight --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
os:
  editPreset: 'nvim'
customCommands:
  - key: "E"
    context: "files, commitFiles"
    description: "Edit using Xcode"
    command: "xed {{ .SelectedPath }}"
  - key: "O"
    context: "files, commitFiles"
    description: "Reveal in Finder"
    command: "open {{ .SelectedPath }}/.."
