startuppopupversion: 1
notARepository: "skip"
reporting: "off"

gui:
  theme:
    lightTheme: true
    selectedRangeBgColor:
      - reverse

git:
  branchLogCmd: "git log --graph"
  paging:
    colorarg: always
    pager: delta --paging=never --diff-highlight
  
