# Taps
tap "homebrew/bundle"
tap "microsoft/git"

# Formulae
brew "bat"
brew "coreutils"
brew "dotbot"
brew "eza"
brew "fd"
brew "fish"
brew "font-fira-code"
brew "fzf"
brew "git"
brew "git-delta"
brew "jq"
brew "lazygit"
brew "lua"
brew "mas"
brew "neovim"
brew "node"
brew "python3"
brew "ripgrep"
brew "ruby"
brew "rustup-init"
brew "tealdeer"
brew "tig"
brew "tmux"

# Casks
cask "alacritty"
cask "appcleaner"
cask "calibre"
cask "git-credential-manager"
cask "google-chrome"
cask "hammerspoon"
cask "karabiner-elements"
cask 'maestral'
cask 'obsidian'
cask 'raycast'
cask "telegram"
cask "the-unarchiver"
cask "visual-studio-code"
cask "xbar"
cask "xcodes"

# Mac App Store Apps
mas "WeChat", id: 836500024
