# Taps
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "melonamin/formulae"

# Formulae
brew "bat"
brew "coreutils"
brew "exa"
brew "fd"
brew "fish"
brew "fzf"
brew "git"
brew "git-delta"
brew "jq"
brew "lazygit"
brew "lua"
brew "mas"
brew "neovim"
brew "node"
brew "python3"
brew "ripgrep"
brew "ruby"
brew "rustup-init"
brew "tealdeer"
brew "tig"
brew "tmux"
brew "universal-ctags"

# Casks
cask "alacritty"
cask "appcleaner"
cask "calibre"
cask "font-fira-code"
cask "google-chrome"
cask "hammerspoon"
cask "karabiner-elements"
cask 'maestral'
cask "telegram"
cask "the-unarchiver"
cask "typora"
cask "visual-studio-code"
cask "xbar"

# Mac App Store Apps
mas "WeChat", id: 836500024
